version: "3.7"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  # api-gateway:
  #   build:
  #     context: .
  #     dockerfile: ./src/FlightBooking.Gateway/Dockerfile
  #   container_name: api-gateway
  #   restart: on-failure
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - flight-service
  #     - bonus-service
  #     - ticket-service

  ticket-service:
    build:
      context: .
      dockerfile: ./src/FlightBooking.TicketService/Dockerfile
    container_name: ticket-service
    restart: on-failure
    environment:
      - DATABASE_URL=Host=postgres;User ID=program;Password=test;Port=5432;Database=tickets;
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  flight-service:
    build:
      context: .
      dockerfile: ./src/FlightBooking.FlightService/Dockerfile
    container_name: flight-service
    restart: on-failure
    environment:
      - DATABASE_URL=Host=postgres;User ID=program;Password=test;Port=5432;Database=flights;
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  bonus-service:
    build:
      context: .
      dockerfile: ./src/FlightBooking.BonusService/Dockerfile
    container_name: bonus-service
    restart: on-failure
    environment:
      - DATABASE_URL=Host=postgres;User ID=program;Password=test;Port=5432;Database=privileges;
    ports:
      - "8050:8050"
    depends_on:
      - postgres

volumes:
  db-data: